// Paste your generated 434-item list inside this array:
const pokemonDatabase = [
    // --- CHUNK 1: Grass & Water Types ---
    { name: "Bulbasaur", nature: "Calm", classTag: "D", habitatTag: "A" },
    { name: "Oddish", nature: "Timid", classTag: "B", habitatTag: "A" },
    { name: "Seedot", nature: "Impish", classTag: "B", habitatTag: "A" },
    { name: "Bellsprout", nature: "Hasty", classTag: "A", habitatTag: "A" },
    { name: "Exeggcute", nature: "Quirky", classTag: "C", habitatTag: "A" },
    { name: "Tangela", nature: "Bashful", classTag: "D", habitatTag: "A" },
    { name: "Chikorita", nature: "Docile", classTag: "D", habitatTag: "A" },
    { name: "Hoppip", nature: "Relaxed", classTag: "B", habitatTag: "A" },
    { name: "Sunkern", nature: "Timid", classTag: "B", habitatTag: "A" },
    { name: "Treecko", nature: "Quiet", classTag: "C", habitatTag: "A" },
    { name: "Shroomish", nature: "Rash", classTag: "A", habitatTag: "A" },
    { name: "Budew", nature: "Gentle", classTag: "D", habitatTag: "A" },
    { name: "Cacnea", nature: "Hardy", classTag: "A", habitatTag: "D" },
    { name: "Tropius", nature: "Gentle", classTag: "D", habitatTag: "A" },
    { name: "Turtwig", nature: "Careful", classTag: "D", habitatTag: "A" },
    { name: "Cherubi", nature: "Jolly", classTag: "B", habitatTag: "A" },
    { name: "Carnivine", nature: "Naughty", classTag: "A", habitatTag: "D" },
    { name: "Snover", nature: "Lonely", classTag: "A", habitatTag: "A" },
    { name: "Snivy", nature: "Sassy", classTag: "C", habitatTag: "A" },
    { name: "Pansage", nature: "Naive", classTag: "C", habitatTag: "A" },
    { name: "Cottonee", nature: "Lax", classTag: "B", habitatTag: "A" },
    { name: "Petilil", nature: "Modest", classTag: "C", habitatTag: "A" },
    { name: "Maractus", nature: "Jolly", classTag: "B", habitatTag: "D" },
    { name: "Deerling", nature: "Mild", classTag: "C", habitatTag: "A" },
    { name: "Foongus", nature: "Impish", classTag: "D", habitatTag: "A" },
    { name: "Ferroseed", nature: "Serious", classTag: "D", habitatTag: "D" },
    { name: "Chespin", nature: "Bold", classTag: "A", habitatTag: "A" },
    { name: "Skiddo", nature: "Docile", classTag: "D", habitatTag: "A" },
    { name: "Rowlet", nature: "Calm", classTag: "C", habitatTag: "A" },
    { name: "Fomantis", nature: "Careful", classTag: "A", habitatTag: "A" },
    { name: "Morelull", nature: "Quiet", classTag: "D", habitatTag: "A" },
    { name: "Bounsweet", nature: "Naive", classTag: "B", habitatTag: "A" },
    { name: "Grookey", nature: "Jolly", classTag: "A", habitatTag: "A" },
    { name: "Gossifleur", nature: "Gentle", classTag: "D", habitatTag: "A" },
    { name: "Applin", nature: "Bashful", classTag: "D", habitatTag: "A" },
    { name: "Sprigatito", nature: "Sassy", classTag: "C", habitatTag: "B" },
    { name: "Smoliv", nature: "Timid", classTag: "C", habitatTag: "A" },
    { name: "Bramblin", nature: "Lonely", classTag: "A", habitatTag: "D" },
    { name: "Capsakid", nature: "Rash", classTag: "A", habitatTag: "D" },
    { name: "Poltchageist", nature: "Careful", classTag: "C", habitatTag: "B" },
    { name: "Squirtle", nature: "Docile", classTag: "D", habitatTag: "C" },
    { name: "Psyduck", nature: "Quirky", classTag: "B", habitatTag: "C" },
    { name: "Poliwag", nature: "Timid", classTag: "B", habitatTag: "C" },
    { name: "Tentacool", nature: "Impish", classTag: "D", habitatTag: "C" },
    { name: "Slowpoke (Kanto)", nature: "Relaxed", classTag: "B", habitatTag: "C" },
    { name: "Seel", nature: "Gentle", classTag: "D", habitatTag: "C" },
    { name: "Horsea", nature: "Bashful", classTag: "C", habitatTag: "C" },
    { name: "Shellder", nature: "Hardy", classTag: "D", habitatTag: "C" },
    // --- CHUNK 2: Water & Fire Types ---
     { name: "Krabby", nature: "Rash", classTag: "A", habitatTag: "B" },
     { name: "Goldeen", nature: "Sassy", classTag: "C", habitatTag: "C" },
     { name: "Staryu", nature: "Quiet", classTag: "D", habitatTag: "C" },
     { name: "Magikarp", nature: "Naive", classTag: "B", habitatTag: "C" },
     { name: "Lapras", nature: "Gentle", classTag: "D", habitatTag: "C" },
     { name: "Totodile", nature: "Jolly", classTag: "A", habitatTag: "C" },
     { name: "Chinchou", nature: "Careful", classTag: "B", habitatTag: "C" },
     { name: "Wooper", nature: "Relaxed", classTag: "D", habitatTag: "C" },
     { name: "Qwilfish (Johto)", nature: "Rash", classTag: "A", habitatTag: "C" },
     { name: "Corsola (Johto)", nature: "Gentle", classTag: "D", habitatTag: "C" },
     { name: "Remoraid", nature: "Serious", classTag: "A", habitatTag: "C" },
     { name: "Mudkip", nature: "Careful", classTag: "A", habitatTag: "C" },
     { name: "Lotad", nature: "Quirky", classTag: "B", habitatTag: "C" },
     { name: "Wingull", nature: "Hasty", classTag: "B", habitatTag: "C" },
     { name: "Carvanha", nature: "Naughty", classTag: "A", habitatTag: "C" },
     { name: "Wailmer", nature: "Jolly", classTag: "D", habitatTag: "C" },
     { name: "Barboach", nature: "Bashful", classTag: "B", habitatTag: "C" },
     { name: "Corphish", nature: "Bold", classTag: "A", habitatTag: "C" },
     { name: "Feebas", nature: "Timid", classTag: "B", habitatTag: "C" },
     { name: "Clamperl", nature: "Careful", classTag: "D", habitatTag: "C" },
     { name: "Relicanth", nature: "Quiet", classTag: "D", habitatTag: "C" },
     { name: "Luvdisc", nature: "Docile", classTag: "C", habitatTag: "C" },
     { name: "Piplup", nature: "Sassy", classTag: "A", habitatTag: "C" },
     { name: "Buizel", nature: "Bold", classTag: "A", habitatTag: "C" },
     { name: "Shellos", nature: "Mild", classTag: "D", habitatTag: "C" },
     { name: "Finneon", nature: "Gentle", classTag: "C", habitatTag: "C" },
     { name: "Mantyke", nature: "Jolly", classTag: "D", habitatTag: "C" },
     { name: "Oshawott", nature: "Rash", classTag: "A", habitatTag: "C" },
     { name: "Panpour", nature: "Naive", classTag: "C", habitatTag: "C" },
     { name: "Tympole", nature: "Jolly", classTag: "B", habitatTag: "C" },
     { name: "Basculin (All Forms)", nature: "Naughty", classTag: "A", habitatTag: "C" },
     { name: "Ducklett", nature: "Lax", classTag: "D", habitatTag: "C" },
     { name: "Frillish", nature: "Quiet", classTag: "C", habitatTag: "C" },
     { name: "Alomomola", nature: "Gentle", classTag: "D", habitatTag: "C" },
     { name: "Froakie", nature: "Hasty", classTag: "B", habitatTag: "C" },
     { name: "Clauncher", nature: "Hardy", classTag: "A", habitatTag: "C" },
     { name: "Popplio", nature: "Jolly", classTag: "C", habitatTag: "C" },
     { name: "Wishiwashi", nature: "Timid", classTag: "D", habitatTag: "C" },
     { name: "Dewpider", nature: "Careful", classTag: "D", habitatTag: "C" },
     { name: "Pyukumuku", nature: "Hardy", classTag: "D", habitatTag: "B" },
     { name: "Bruxish", nature: "Impish", classTag: "A", habitatTag: "C" },
     { name: "Sobble", nature: "Timid", classTag: "B", habitatTag: "C" },
     { name: "Chewtle", nature: "Bold", classTag: "A", habitatTag: "C" },
     { name: "Arrokuda", nature: "Hasty", classTag: "A", habitatTag: "C" },
     { name: "Quaxly", nature: "Serious", classTag: "B", habitatTag: "C" },
     { name: "Wiglett", nature: "Timid", classTag: "B", habitatTag: "B" },
     { name: "Finizen", nature: "Jolly", classTag: "D", habitatTag: "C" },
     { name: "Veluza", nature: "Rash", classTag: "A", habitatTag: "C" },
     { name: "Dondozo", nature: "Calm", classTag: "D", habitatTag: "C" },
     { name: "Charmander", nature: "Docile", classTag: "C", habitatTag: "A" },
     { name: "Vulpix", nature: "Quiet", classTag: "D", habitatTag: "A" },
     { name: "Growlithe (Kanto)", nature: "Brave", classTag: "D", habitatTag: "B" },
     // --- CHUNK 3: Fire & Bug Types ---
    { name: "Growlithe (Hisui)", nature: "Careful", classTag: "D", habitatTag: "A" },
    { name: "Ponyta (Kanto)", nature: "Hasty", classTag: "B", habitatTag: "A" },
    { name: "Cyndaquil", nature: "Timid", classTag: "B", habitatTag: "A" },
    { name: "Slugma", nature: "Relaxed", classTag: "C", habitatTag: "D" },
    { name: "Magby", nature: "Rash", classTag: "A", habitatTag: "A" },
    { name: "Torchic", nature: "Naive", classTag: "C", habitatTag: "A" },
    { name: "Numel", nature: "Relaxed", classTag: "D", habitatTag: "A" },
    { name: "Torkoal", nature: "Docile", classTag: "D", habitatTag: "D" },
    { name: "Chimchar", nature: "Jolly", classTag: "A", habitatTag: "A" },
    { name: "Tepig", nature: "Rash", classTag: "A", habitatTag: "A" },
    { name: "Pansear", nature: "Naive", classTag: "C", habitatTag: "A" },
    { name: "Darumaka", nature: "Rash", classTag: "A", habitatTag: "D" },
    { name: "Heatmor", nature: "Serious", classTag: "C", habitatTag: "D" },
    { name: "Fennekin", nature: "Mild", classTag: "C", habitatTag: "A" },
    { name: "Fletchling", nature: "Hasty", classTag: "B", habitatTag: "A" },
    { name: "Litleo", nature: "Bold", classTag: "A", habitatTag: "A" },
    { name: "Litten", nature: "Quiet", classTag: "A", habitatTag: "B" },
    { name: "Oricorio (Baile)", nature: "Sassy", classTag: "C", habitatTag: "A" },
    { name: "Turtonator", nature: "Hardy", classTag: "D", habitatTag: "A" },
    { name: "Scorbunny", nature: "Jolly", classTag: "A", habitatTag: "B" },
    { name: "Sizzlipede", nature: "Naughty", classTag: "A", habitatTag: "A" },
    { name: "Fuecoco", nature: "Lax", classTag: "C", habitatTag: "C" },
    { name: "Charcadet", nature: "Brave", classTag: "A", habitatTag: "A" },
    { name: "Caterpie", nature: "Naive", classTag: "B", habitatTag: "A" },
    { name: "Weedle", nature: "Rash", classTag: "A", habitatTag: "A" },
    { name: "Paras", nature: "Quiet", classTag: "D", habitatTag: "A" },
    { name: "Venonat", nature: "Timid", classTag: "B", habitatTag: "A" },
    { name: "Scyther", nature: "Adamant", classTag: "A", habitatTag: "A" },
    { name: "Pinsir", nature: "Bold", classTag: "A", habitatTag: "A" },
    { name: "Ledyba", nature: "Timid", classTag: "D", habitatTag: "A" },
    { name: "Spinarak", nature: "Careful", classTag: "A", habitatTag: "A" },
    { name: "Yanma", nature: "Hasty", classTag: "B", habitatTag: "C" },
    { name: "Pineco", nature: "Careful", classTag: "D", habitatTag: "A" },
    { name: "Shuckle", nature: "Relaxed", classTag: "D", habitatTag: "A" },
    { name: "Heracross", nature: "Brave", classTag: "A", habitatTag: "A" },
    { name: "Wurmple", nature: "Docile", classTag: "D", habitatTag: "A" },
    { name: "Surskit", nature: "Gentle", classTag: "B", habitatTag: "C" },
    { name: "Nincada", nature: "Quiet", classTag: "D", habitatTag: "A" },
    { name: "Volbeat", nature: "Jolly", classTag: "C", habitatTag: "A" },
    { name: "Illumise", nature: "Sassy", classTag: "C", habitatTag: "A" },
    { name: "Kricketot", nature: "Quirky", classTag: "C", habitatTag: "A" },
    { name: "Burmy", nature: "Mild", classTag: "D", habitatTag: "A" },
    { name: "Combee", nature: "Serious", classTag: "C", habitatTag: "A" },
    { name: "Sewaddle", nature: "Gentle", classTag: "D", habitatTag: "A" },
    { name: "Venipede", nature: "Naughty", classTag: "A", habitatTag: "A" },
    { name: "Dwebble", nature: "Bashful", classTag: "D", habitatTag: "D" },
    { name: "Karrablast", nature: "Rash", classTag: "A", habitatTag: "C" },
    { name: "Joltik", nature: "Impish", classTag: "C", habitatTag: "D" },
    { name: "Shelmet", nature: "Timid", classTag: "D", habitatTag: "C" },
    { name: "Durant", nature: "Serious", classTag: "D", habitatTag: "D" },
    // --- CHUNK 4: Bug & Normal Types ---
    { name: "Larvesta", nature: "Bold", classTag: "A", habitatTag: "A" },
    { name: "Scatterbug", nature: "Naive", classTag: "B", habitatTag: "A" },
    { name: "Grubbin", nature: "Hardy", classTag: "A", habitatTag: "A" },
    { name: "Cutiefly", nature: "Jolly", classTag: "C", habitatTag: "B" },
    { name: "Wimpod", nature: "Timid", classTag: "B", habitatTag: "C" },
    { name: "Blipbug", nature: "Modest", classTag: "C", habitatTag: "B" },
    { name: "Tarountula", nature: "Careful", classTag: "D", habitatTag: "A" },
    { name: "Nymble", nature: "Hasty", classTag: "B", habitatTag: "B" },
    { name: "Rellor", nature: "Serious", classTag: "C", habitatTag: "D" },
    { name: "Pidgey", nature: "Gentle", classTag: "B", habitatTag: "B" },
    { name: "Rattata (Kanto)", nature: "Hasty", classTag: "B", habitatTag: "B" },
    { name: "Spearow", nature: "Rash", classTag: "A", habitatTag: "B" },
    { name: "Igglybuff", nature: "Jolly", classTag: "D", habitatTag: "B" },
    { name: "Meowth (Kanto)", nature: "Impish", classTag: "B", habitatTag: "B" },
    { name: "Farfetch’d (Kanto)", nature: "Serious", classTag: "A", habitatTag: "B" },
    { name: "Doduo", nature: "Hasty", classTag: "B", habitatTag: "B" },
    { name: "Lickitung", nature: "Quirky", classTag: "D", habitatTag: "B" },
    { name: "Happiny", nature: "Naive", classTag: "D", habitatTag: "B" },
    { name: "Kangaskhan", nature: "Brave", classTag: "D", habitatTag: "B" },
    { name: "Munchlax", nature: "Lax", classTag: "D", habitatTag: "A" },
    { name: "Eevee", nature: "Docile", classTag: "C", habitatTag: "B" },
    { name: "Porygon", nature: "Quiet", classTag: "C", habitatTag: "B" },
    { name: "Tauros (Kanto)", nature: "Bold", classTag: "A", habitatTag: "B" },
    { name: "Ditto", nature: "Quirky", classTag: "D", habitatTag: "B" },
    { name: "Sentret", nature: "Timid", classTag: "B", habitatTag: "B" },
    { name: "Hoothoot", nature: "Calm", classTag: "C", habitatTag: "A" },
    { name: "Aipom", nature: "Jolly", classTag: "B", habitatTag: "A" },
    { name: "Girafarig", nature: "Quiet", classTag: "C", habitatTag: "B" },
    { name: "Dunsparce", nature: "Bashful", classTag: "D", habitatTag: "D" },
    { name: "Teddiursa", nature: "Naive", classTag: "A", habitatTag: "A" },
    { name: "Stantler", nature: "Calm", classTag: "A", habitatTag: "B" },
    { name: "Smeargle", nature: "Quirky", classTag: "B", habitatTag: "B" },
    { name: "Miltank", nature: "Gentle", classTag: "D", habitatTag: "B" },
    { name: "Zigzagoon (Hoenn)", nature: "Rash", classTag: "B", habitatTag: "B" },
    { name: "Taillow", nature: "Brave", classTag: "B", habitatTag: "B" },
    { name: "Slakoth", nature: "Lax", classTag: "D", habitatTag: "A" },
    { name: "Whismur", nature: "Timid", classTag: "D", habitatTag: "D" },
    { name: "Azurill", nature: "Naive", classTag: "D", habitatTag: "C" },
    { name: "Skitty", nature: "Jolly", classTag: "B", habitatTag: "B" },
    { name: "Spinda", nature: "Quirky", classTag: "C", habitatTag: "A" },
    { name: "Swablu", nature: "Gentle", classTag: "C", habitatTag: "B" },
    { name: "Zangoose", nature: "Rash", classTag: "A", habitatTag: "B" },
    { name: "Castform", nature: "Mild", classTag: "C", habitatTag: "B" },
    { name: "Kecleon", nature: "Quiet", classTag: "C", habitatTag: "A" },
    { name: "Starly", nature: "Hasty", classTag: "B", habitatTag: "B" },
    { name: "Bidoof", nature: "Calm", classTag: "D", habitatTag: "C" },
    { name: "Buneary", nature: "Timid", classTag: "B", habitatTag: "A" },
    { name: "Glameow", nature: "Sassy", classTag: "B", habitatTag: "B" },
    { name: "Chatot", nature: "Jolly", classTag: "C", habitatTag: "A" },
    { name: "Patrat", nature: "Careful", classTag: "A", habitatTag: "B" },
    // --- CHUNK 5: Normal, Electric & Ground Types ---
    { name: "Lillipup", nature: "Brave", classTag: "A", habitatTag: "B" },
    { name: "Pidove", nature: "Docile", classTag: "A", habitatTag: "B" },
    { name: "Zorua (Hisui)", nature: "Lonely", classTag: "C", habitatTag: "D" },
    { name: "Minccino", nature: "Careful", classTag: "C", habitatTag: "B" },
    { name: "Deerling", nature: "Mild", classTag: "C", habitatTag: "A" },
    { name: "Bouffalant", nature: "Rash", classTag: "A", habitatTag: "B" },
    { name: "Rufflet", nature: "Bold", classTag: "A", habitatTag: "A" },
    { name: "Bunnelby", nature: "Adamant", classTag: "C", habitatTag: "B" },
    { name: "Fletchling", nature: "Hasty", classTag: "C", habitatTag: "B" },
    { name: "Furfrou", nature: "Sassy", classTag: "D", habitatTag: "B" },
    { name: "Pikipek", nature: "Adamant", classTag: "A", habitatTag: "A" },
    { name: "Yungoos", nature: "Rash", classTag: "A", habitatTag: "B" },
    { name: "Stufful", nature: "Rash", classTag: "A", habitatTag: "A" },
    { name: "Oranguru", nature: "Calm", classTag: "C", habitatTag: "A" },
    { name: "Komala", nature: "Relaxed", classTag: "D", habitatTag: "A" },
    { name: "Drampa", nature: "Gentle", classTag: "C", habitatTag: "A" },
    { name: "Skwovet", nature: "Lax", classTag: "D", habitatTag: "B" },
    { name: "Wooloo", nature: "Gentle", classTag: "D", habitatTag: "B" },
    { name: "Lechonk", nature: "Timid", classTag: "D", habitatTag: "B" },
    { name: "Tandemaus", nature: "Docile", classTag: "C", habitatTag: "B" },
    { name: "Squawkabilly", nature: "Sassy", classTag: "C", habitatTag: "B" },
    { name: "Magnemite", nature: "Quiet", classTag: "C", habitatTag: "B" },
    { name: "Pichu", nature: "Naive", classTag: "C", habitatTag: "B" },
    { name: "Voltorb (Kanto)", nature: "Rash", classTag: "C", habitatTag: "B" },
    { name: "Voltorb (Hisui)", nature: "Jolly", classTag: "C", habitatTag: "A" },
    { name: "Elekid", nature: "Naughty", classTag: "A", habitatTag: "B" },
    { name: "Mareep", nature: "Gentle", classTag: "C", habitatTag: "B" },
    { name: "Electrike", nature: "Hasty", classTag: "C", habitatTag: "B" },
    { name: "Plusle", nature: "Jolly", classTag: "C", habitatTag: "B" },
    { name: "Minun", nature: "Jolly", classTag: "C", habitatTag: "B" },
    { name: "Shinx", nature: "Bold", classTag: "A", habitatTag: "B" },
    { name: "Pachirisu", nature: "Impish", classTag: "C", habitatTag: "A" },
    { name: "Rotom", nature: "Impish", classTag: "C", habitatTag: "B" },
    { name: "Blitzle", nature: "Hasty", classTag: "C", habitatTag: "B" },
    { name: "Emolga", nature: "Sassy", classTag: "C", habitatTag: "A" },
    { name: "Tynamo", nature: "Timid", classTag: "C", habitatTag: "D" },
    { name: "Helioptile", nature: "Timid", classTag: "C", habitatTag: "D" },
    { name: "Dedenne", nature: "Lax", classTag: "C", habitatTag: "B" },
    { name: "Oricorio (Pom-Pom)", nature: "Jolly", classTag: "C", habitatTag: "B" },
    { name: "Togedemaru", nature: "Bold", classTag: "D", habitatTag: "A" },
    { name: "Yamper", nature: "Jolly", classTag: "D", habitatTag: "B" },
    { name: "Toxel", nature: "Relaxed", classTag: "C", habitatTag: "B" },
    { name: "Pincurchin", nature: "Docile", classTag: "D", habitatTag: "C" },
    { name: "Morpeko", nature: "Rash", classTag: "C", habitatTag: "B" },
    { name: "Pawmi", nature: "Gentle", classTag: "A", habitatTag: "B" },
    { name: "Tadbulb", nature: "Relaxed", classTag: "D", habitatTag: "C" },
    { name: "Wattrel", nature: "Hasty", classTag: "C", habitatTag: "C" },
    { name: "Sandshrew", nature: "Hardy", classTag: "D", habitatTag: "D" },
    { name: "Diglett (Kanto)", nature: "Timid", classTag: "C", habitatTag: "D" },
    { name: "Diglett (Alola)", nature: "Careful", classTag: "C", habitatTag: "D" },
    { name: "Cubone", nature: "Lonely", classTag: "A", habitatTag: "A" },
    // --- CHUNK 6: Ground, Rock & Poison Types ---
    { name: "Rhyhorn", nature: "Rash", classTag: "A", habitatTag: "A" },
    { name: "Gligar", nature: "Impish", classTag: "D", habitatTag: "A" },
    { name: "Phanpy", nature: "Jolly", classTag: "A", habitatTag: "D" },
    { name: "Trapinch", nature: "Adamant", classTag: "A", habitatTag: "D" },
    { name: "Baltoy", nature: "Quiet", classTag: "C", habitatTag: "D" },
    { name: "Hippopotas", nature: "Lax", classTag: "D", habitatTag: "D" },
    { name: "Drilbur", nature: "Adamant", classTag: "A", habitatTag: "D" },
    { name: "Sandile", nature: "Naughty", classTag: "A", habitatTag: "D" },
    { name: "Yamask (Galar)", nature: "Quiet", classTag: "D", habitatTag: "D" },
    { name: "Stunfisk (Unova)", nature: "Relaxed", classTag: "D", habitatTag: "C" },
    { name: "Stunfisk (Galar)", nature: "Bold", classTag: "D", habitatTag: "D" },
    { name: "Golett", nature: "Serious", classTag: "A", habitatTag: "D" },
    { name: "Mudbray", nature: "Adamant", classTag: "A", habitatTag: "A" },
    { name: "Silicobra", nature: "Timid", classTag: "D", habitatTag: "D" },
    { name: "Toedscool", nature: "Hasty", classTag: "B", habitatTag: "A" },
    { name: "Geodude (Kanto)", nature: "Hardy", classTag: "D", habitatTag: "A" },
    { name: "Geodude (Alola)", nature: "Rash", classTag: "D", habitatTag: "A" },
    { name: "Onix", nature: "Adamant", classTag: "D", habitatTag: "D" },
    { name: "Larvitar", nature: "Naughty", classTag: "A", habitatTag: "A" },
    { name: "Nosepass", nature: "Serious", classTag: "D", habitatTag: "D" },
    { name: "Lunatone", nature: "Quiet", classTag: "C", habitatTag: "D" },
    { name: "Solrock", nature: "Bold", classTag: "A", habitatTag: "D" },
    { name: "Bonsly", nature: "Timid", classTag: "D", habitatTag: "A" },
    { name: "Roggenrola", nature: "Docile", classTag: "D", habitatTag: "D" },
    { name: "Binacle", nature: "Rash", classTag: "A", habitatTag: "C" },
    { name: "Carbink", nature: "Calm", classTag: "D", habitatTag: "D" },
    { name: "Rockruff", nature: "Jolly", classTag: "A", habitatTag: "A" },
    { name: "Minior", nature: "Naive", classTag: "B", habitatTag: "A" },
    { name: "Rolycoly", nature: "Hardy", classTag: "D", habitatTag: "D" },
    { name: "Stonjourner", nature: "Relaxed", classTag: "D", habitatTag: "A" },
    { name: "Nacli", nature: "Careful", classTag: "D", habitatTag: "D" },
    { name: "Glimmet", nature: "Quiet", classTag: "C", habitatTag: "D" },
    { name: "Klawf", nature: "Adamant", classTag: "D", habitatTag: "C" },
    { name: "Ekans", nature: "Adamant", classTag: "A", habitatTag: "A" },
    { name: "Nidoran (Female)", nature: "Docile", classTag: "D", habitatTag: "A" },
    { name: "Nidoran (Male)", nature: "Bold", classTag: "A", habitatTag: "A" },
    { name: "Zubat", nature: "Hasty", classTag: "B", habitatTag: "D" },
    { name: "Grimer (Kanto)", nature: "Lax", classTag: "D", habitatTag: "B" },
    { name: "Grimer (Alola)", nature: "Impish", classTag: "A", habitatTag: "B" },
    { name: "Koffing", nature: "Jolly", classTag: "D", habitatTag: "B" },
    { name: "Wooper (Paldea)", nature: "Relaxed", classTag: "D", habitatTag: "C" },
    { name: "Gulpin", nature: "Lax", classTag: "D", habitatTag: "A" },
    { name: "Seviper", nature: "Rash", classTag: "C", habitatTag: "A" },
    { name: "Stunky", nature: "Sassy", classTag: "D", habitatTag: "A" },
    { name: "Skorupi", nature: "Careful", classTag: "D", habitatTag: "D" },
    { name: "Croagunk", nature: "Impish", classTag: "A", habitatTag: "C" },
    { name: "Trubbish", nature: "Naive", classTag: "D", habitatTag: "B" },
    { name: "Skrelp", nature: "Quiet", classTag: "D", habitatTag: "C" },
    { name: "Mareanie", nature: "Naughty", classTag: "D", habitatTag: "C" },
    { name: "Salandit", nature: "Impish", classTag: "B", habitatTag: "A" },
    { name: "Shroodle", nature: "Hasty", classTag: "B", habitatTag: "A" },
    // --- CHUNK 7: Ghost, Psychic, Fairy & Steel Types ---
    { name: "Gastly", nature: "Impish", classTag: "C", habitatTag: "D" },
    { name: "Misdreavus", nature: "Naughty", classTag: "C", habitatTag: "A" },
    { name: "Corsola (Galar)", nature: "Lonely", classTag: "C", habitatTag: "C" },
    { name: "Shuppet", nature: "Spiteful", classTag: "B", habitatTag: "B" },
    { name: "Duskull", nature: "Careful", classTag: "B", habitatTag: "A" },
    { name: "Drifloon", nature: "Naive", classTag: "C", habitatTag: "B" },
    { name: "Yamask (Unova)", nature: "Quiet", classTag: "C", habitatTag: "D" },
    { name: "Litwick", nature: "Timid", classTag: "C", habitatTag: "A" },
    { name: "Phantump", nature: "Lonely", classTag: "D", habitatTag: "A" },
    { name: "Pumpkaboo", nature: "Jolly", classTag: "C", habitatTag: "B" },
    { name: "Oricorio (Sensu Style)", nature: "Calm", classTag: "C", habitatTag: "A" },
    { name: "Sandygast", nature: "Impish", classTag: "C", habitatTag: "C" },
    { name: "Mimikyu", nature: "Lonely", classTag: "B", habitatTag: "A" },
    { name: "Dhelmise", nature: "Adamant", classTag: "A", habitatTag: "C" },
    { name: "Sinistea", nature: "Quiet", classTag: "C", habitatTag: "B" },
    { name: "Greavard", nature: "Docile", classTag: "C", habitatTag: "D" },
    { name: "Gimmighoul", nature: "Hasty", classTag: "B", habitatTag: "D" },
    { name: "Abra", nature: "Timid", classTag: "C", habitatTag: "A" },
    { name: "Ponyta (Galar)", nature: "Gentle", classTag: "D", habitatTag: "A" },
    { name: "Slowpoke (Galar)", nature: "Relaxed", classTag: "D", habitatTag: "C" },
    { name: "Drowzee", nature: "Quiet", classTag: "C", habitatTag: "B" },
    { name: "Natu", nature: "Quiet", classTag: "B", habitatTag: "A" },
    { name: "Ralts", nature: "Timid", classTag: "C", habitatTag: "B" },
    { name: "Spoink", nature: "Jolly", classTag: "A", habitatTag: "A" },
    { name: "Wynaut", nature: "Jolly", classTag: "D", habitatTag: "D" },
    { name: "Chingling", nature: "Quiet", classTag: "C", habitatTag: "D" },
    { name: "Mime Jr.", nature: "Impish", classTag: "C", habitatTag: "B" },
    { name: "Munna", nature: "Calm", classTag: "D", habitatTag: "A" },
    { name: "Woobat", nature: "Naive", classTag: "B", habitatTag: "D" },
    { name: "Sigilyph", nature: "Serious", classTag: "C", habitatTag: "D" },
    { name: "Gothita", nature: "Modest", classTag: "C", habitatTag: "B" },
    { name: "Solosis", nature: "Quiet", classTag: "C", habitatTag: "A" },
    { name: "Elgyem", nature: "Quiet", classTag: "C", habitatTag: "D" },
    { name: "Espurr", nature: "Bashful", classTag: "C", habitatTag: "B" },
    { name: "Oricorio (Pa'u Style)", nature: "Relaxed", classTag: "C", habitatTag: "B" },
    { name: "Hatenna", nature: "Quiet", classTag: "D", habitatTag: "A" },
    { name: "Indeedee", nature: "Docile", classTag: "D", habitatTag: "B" },
    { name: "Flittle", nature: "Hasty", classTag: "C", habitatTag: "D" },
    { name: "Cleffa", nature: "Timid", classTag: "C", habitatTag: "A" },
    { name: "Togepi", nature: "Jolly", classTag: "D", habitatTag: "A" },
    { name: "Snubbull", nature: "Timid", classTag: "A", habitatTag: "B" },
    { name: "Flabébé", nature: "Gentle", classTag: "D", habitatTag: "B" },
    { name: "Spritzee", nature: "Quiet", classTag: "D", habitatTag: "A" },
    { name: "Swirlix", nature: "Jolly", classTag: "C", habitatTag: "B" },
    { name: "Comfey", nature: "Gentle", classTag: "D", habitatTag: "B" },
    { name: "Milcery", nature: "Docile", classTag: "C", habitatTag: "B" },
    { name: "Fidough", nature: "Jolly", classTag: "D", habitatTag: "B" },
    { name: "Tinkatink", nature: "Impish", classTag: "C", habitatTag: "A" },
    { name: "Meowth (Galar)", nature: "Adamant", classTag: "A", habitatTag: "B" },
    { name: "Skarmory", nature: "Impish", classTag: "A", habitatTag: "A" },
    // --- CHUNK 8: Steel, Dark & Fighting Types ---
    { name: "Mawile", nature: "Naughty", classTag: "B", habitatTag: "D" },
    { name: "Aron", nature: "Hardy", classTag: "D", habitatTag: "A" },
    { name: "Beldum", nature: "Quiet", classTag: "D", habitatTag: "A" },
    { name: "Bronzor", nature: "Calm", classTag: "D", habitatTag: "D" },
    { name: "Klink", nature: "Serious", classTag: "D", habitatTag: "B" },
    { name: "Honedge", nature: "Quiet", classTag: "D", habitatTag: "D" },
    { name: "Klefki", nature: "Bold", classTag: "D", habitatTag: "B" },
    { name: "Cufant", nature: "Docile", classTag: "A", habitatTag: "D" },
    { name: "Duraludon", nature: "Rash", classTag: "D", habitatTag: "A" },
    { name: "Varoom", nature: "Hasty", classTag: "A", habitatTag: "B" },
    { name: "Orthworm", nature: "Relaxed", classTag: "D", habitatTag: "D" },
    { name: "Rattata (Alola)", nature: "Naughty", classTag: "B", habitatTag: "B" },
    { name: "Meowth (Alola)", nature: "Sassy", classTag: "B", habitatTag: "B" },
    { name: "Murkrow", nature: "Impish", classTag: "B", habitatTag: "A" },
    { name: "Qwilfish (Hisui)", nature: "Rash", classTag: "A", habitatTag: "C" },
    { name: "Sneasel", nature: "Hasty", classTag: "B", habitatTag: "A" },
    { name: "Houndour", nature: "Adamant", classTag: "B", habitatTag: "A" },
    { name: "Poochyena", nature: "Timid", classTag: "A", habitatTag: "B" },
    { name: "Zigzagoon (Galar)", nature: "Rash", classTag: "B", habitatTag: "B" },
    { name: "Sableye", nature: "Impish", classTag: "D", habitatTag: "D" },
    { name: "Absol", nature: "Careful", classTag: "A", habitatTag: "A" },
    { name: "Purrloin", nature: "Impish", classTag: "B", habitatTag: "B" },
    { name: "Zorua (Unova)", nature: "Quirky", classTag: "B", habitatTag: "A" },
    { name: "Pawniard", nature: "Adamant", classTag: "A", habitatTag: "A" },
    { name: "Vullaby", nature: "Naughty", classTag: "D", habitatTag: "A" },
    { name: "Deino", nature: "Rash", classTag: "C", habitatTag: "D" },
    { name: "Inkay", nature: "Naughty", classTag: "C", habitatTag: "C" },
    { name: "Nickit", nature: "Impish", classTag: "B", habitatTag: "A" },
    { name: "Impidimp", nature: "Impish", classTag: "C", habitatTag: "A" },
    { name: "Maschiff", nature: "Bold", classTag: "A", habitatTag: "B" },
    { name: "Scraggy", nature: "Bold", classTag: "D", habitatTag: "D" },
    { name: "Mankey", nature: "Rash", classTag: "A", habitatTag: "A" },
    { name: "Machop", nature: "Hardy", classTag: "A", habitatTag: "A" },
    { name: "Tyrogue", nature: "Adamant", classTag: "A", habitatTag: "B" },
    { name: "Farfetch'd (Galar)", nature: "Adamant", classTag: "A", habitatTag: "B" },
    { name: "Tauros (Combat Breed)", nature: "Adamant", classTag: "A", habitatTag: "B" },
    { name: "Tauros (Blaze Breed)", nature: "Adamant", classTag: "A", habitatTag: "B" },
    { name: "Tauros (Aqua Breed)", nature: "Adamant", classTag: "A", habitatTag: "B" },
    { name: "Sneasel (Hisui)", nature: "Jolly", classTag: "B", habitatTag: "A" },
    { name: "Meditite", nature: "Quiet", classTag: "A", habitatTag: "A" },
    { name: "Riolu", nature: "Brave", classTag: "B", habitatTag: "A" },
    { name: "Timburr", nature: "Hardy", classTag: "A", habitatTag: "A" },
    { name: "Throh", nature: "Serious", classTag: "D", habitatTag: "A" },
    { name: "Sawk", nature: "Serious", classTag: "A", habitatTag: "A" },
    { name: "Mienfoo", nature: "Careful", classTag: "B", habitatTag: "A" },
    { name: "Pancham", nature: "Naughty", classTag: "A", habitatTag: "A" },
    { name: "Hawlucha", nature: "Brave", classTag: "B", habitatTag: "A" },
    { name: "Crabrawler", nature: "Bold", classTag: "A", habitatTag: "C" },
    { name: "Passimian", nature: "Adamant", classTag: "A", habitatTag: "A" },
    { name: "Clobbopus", nature: "Impish", classTag: "A", habitatTag: "C" },
    { name: "Falinks", nature: "Serious", classTag: "D", habitatTag: "D" },
    // --- CHUNK 9: Ice, Flying & Dragon Types ---
    { name: "Sandshrew (Alola)", nature: "Adamant", classTag: "D", habitatTag: "A" },
    { name: "Vulpix (Alola)", nature: "Timid", classTag: "B", habitatTag: "A" },
    { name: "Swinub", nature: "Naive", classTag: "B", habitatTag: "A" },
    { name: "Delibird", nature: "Jolly", classTag: "B", habitatTag: "A" },
    { name: "Smoochum", nature: "Sassy", classTag: "C", habitatTag: "B" },
    { name: "Snorunt", nature: "Quirky", classTag: "B", habitatTag: "A" },
    { name: "Spheal", nature: "Jolly", classTag: "B", habitatTag: "C" },
    { name: "Darumaka (Galar)", nature: "Rash", classTag: "A", habitatTag: "A" },
    { name: "Vanillite", nature: "Docile", classTag: "C", habitatTag: "A" },
    { name: "Cubchoo", nature: "Timid", classTag: "A", habitatTag: "A" },
    { name: "Cryogonal", nature: "Serious", classTag: "D", habitatTag: "A" },
    { name: "Bergmite", nature: "Hardy", classTag: "D", habitatTag: "A" },
    { name: "Snom", nature: "Timid", classTag: "D", habitatTag: "A" },
    { name: "Eiscue", nature: "Relaxed", classTag: "D", habitatTag: "C" },
    { name: "Cetoddle", nature: "Gentle", classTag: "D", habitatTag: "A" },
    { name: "Noibat", nature: "Timid", classTag: "B", habitatTag: "D" },
    { name: "Rookidee", nature: "Brave", classTag: "B", habitatTag: "B" },
    { name: "Cramorant", nature: "Docile", classTag: "C", habitatTag: "C" },
    { name: "Bombirdier", nature: "Naughty", classTag: "A", habitatTag: "A" },
    { name: "Flamigo", nature: "Bold", classTag: "B", habitatTag: "C" },
    { name: "Dratini", nature: "Gentle", classTag: "C", habitatTag: "C" },
    { name: "Bagon", nature: "Adamant", classTag: "A", habitatTag: "A" },
    { name: "Gible", nature: "Naughty", classTag: "A", habitatTag: "D" },
    { name: "Axew", nature: "Brave", classTag: "A", habitatTag: "D" },
    { name: "Druddigon", nature: "Impish", classTag: "A", habitatTag: "D" },
    { name: "Goomy", nature: "Docile", classTag: "D", habitatTag: "C" },
    { name: "Jangmo-o", nature: "Brave", classTag: "D", habitatTag: "A" },
    { name: "Dreepy", nature: "Timid", classTag: "B", habitatTag: "C" },
    { name: "Cyclizar", nature: "Jolly", classTag: "B", habitatTag: "B" },
    { name: "Tatsugiri", nature: "Impish", classTag: "C", habitatTag: "C" },
    { name: "Frigibax", nature: "Hardy", classTag: "A", habitatTag: "A" }
];
const answerScores = {
    q1: { A: { Brave: 2, Rash: 1 }, B: { Careful: 2, Serious: 1 }, C: { Quiet: 2, Timid: 1 }, D: { Jolly: 2, Gentle: 1 } },
    q2: { A: { Adamant: 2, Impish: 1 }, B: { Mild: 2, Modest: 1 }, C: { Timid: 2, Bashful: 1 }, D: { Quirky: 2, Lonely: 1 } },
    q3: { A: { Jolly: 2, Naive: 1 }, B: { Sassy: 2, Lax: 1 }, C: { Hardy: 2, Bold: 1 }, D: { Careful: 2, Docile: 1 } },
    q4: { A: { Bold: 2, Brave: 1 }, B: { Naive: 2, Impish: 1 }, C: { Quiet: 2, Careful: 1 }, D: { Bashful: 2, Relaxed: 1 } },
    q5: { A: { Hasty: 2, Rash: 1 }, B: { Gentle: 2, Docile: 1 }, C: { Impish: 2, Quirky: 1 }, D: { Relaxed: 2, Lax: 1 } },
    q6: { A: { Serious: 2, Hardy: 1 }, B: { Rash: 2, Naughty: 1 }, C: { Relaxed: 2, Lax: 1 }, D: { Lonely: 2, Gentle: 1 } },
    q7: { A: { Jolly: 2, Sassy: 1 }, B: { Careful: 2, Quiet: 1 }, C: { Lax: 2, Relaxed: 1 }, D: { Mild: 2, Modest: 1 } },
    q8: { A: { Adamant: 2, Bold: 1 }, B: { Naive: 2, Jolly: 1 }, C: { Impish: 2, Naughty: 1 }, D: { Gentle: 2, Docile: 1 } },
    q9: { A: { Bold: 2, Hasty: 1 }, B: { Careful: 2, Serious: 1 }, C: { Naive: 2, Rash: 1 }, D: { Quiet: 2, Calm: 1 } },
    q10: { A: { Serious: 2, Brave: 1 }, B: { Gentle: 2, Calm: 1 }, C: { Timid: 2, Lonely: 1 }, D: { Sassy: 2, Impish: 1 } },
    q11: { A: { Calm: 2, Gentle: 1 }, B: { Jolly: 2, Sassy: 1 }, C: { Relaxed: 2, Lax: 1 }, D: { Mild: 2, Quiet: 1 } },
    q12: { A: { Gentle: 2, Docile: 1 }, B: { Serious: 2, Careful: 1 }, C: { Bold: 2, Hasty: 1 }, D: { Timid: 2, Bashful: 1 } },
    q13: { A: { Hasty: 2, Rash: 1 }, B: { Impish: 2, Naughty: 1 }, C: { Relaxed: 2, Lax: 1 }, D: { Serious: 2, Careful: 1 } },
    q14: { A: { Bold: 2, Jolly: 1 }, B: { Lax: 2, Naive: 1 }, C: { Quiet: 2, Bashful: 1 }, D: { Timid: 2, Careful: 1 } },
    q15: { A: {}, B: {}, C: {}, D: {} }
};

function submitQuiz() {
    const nameElement = document.getElementById("player-name");
    if (!nameElement || !nameElement.value) {
        alert("Please enter your name first!");
        return;
    }

    let formElement = document.getElementById("icebreaker-form");
    let formData = new FormData(formElement);
    let natureScores = {};

    for (let i = 1; i <= 14; i++) {
        let answer = formData.get(`q${i}`);
        if (!answer) {
            alert(`Please answer Question ${i}!`);
            return;
        }
        let scores = answerScores[`q${i}`][answer];
        if (scores) {
            for (let nature in scores) {
                natureScores[nature] = (natureScores[nature] || 0) + scores[nature];
            }
        }
    }

    let q15ClassTag = formData.get("q15");
    if (!q15ClassTag) {
        alert("Please answer Question 15!");
        return;
    }

    let highestScore = -1;
    let winningNature = "Hardy";
    for (let nature in natureScores) {
        if (natureScores[nature] > highestScore) {
            highestScore = natureScores[nature];
            winningNature = nature;
        }
    }

    let candidates = pokemonDatabase.filter(p => p.nature === winningNature);
    let finalPokemon;

    if (candidates.length > 0) {
        let classMatches = candidates.filter(p => p.classTag === q15ClassTag);
        finalPokemon = classMatches.length > 0 ? classMatches[0] : candidates[0];
    } else {
        finalPokemon = pokemonDatabase[0] || { name: "Eevee", nature: winningNature };
    }

    let natureInput = document.getElementById("secret-nature") || document.createElement("input");
    natureInput.type = "hidden"; natureInput.name = "Assigned_Nature"; natureInput.id = "secret-nature";
    natureInput.value = winningNature;
    formElement.appendChild(natureInput);

    let pokemonInput = document.getElementById("secret-pokemon") || document.createElement("input");
    pokemonInput.type = "hidden"; pokemonInput.name = "Assigned_Pokemon"; pokemonInput.id = "secret-pokemon";
    pokemonInput.value = finalPokemon.name;
    formElement.appendChild(pokemonInput);

    formElement.submit();
}